### ISSUE TITLE
Information Exposure (Upgrade Azure.Storage.Blobs to 12.13.0)

### ISSUE THREAD

**Issue by saigkill** [wilder-minds/AzureImageStorageService#1]
Currently Azure.Storage.Blobs is vulnerable.
Introduced: src@1.0.0 > WilderMinds.AzureImageStorageService@0.4.1 > Azure.Storage.Blobs@12.7.0

Please upgrade the dependencies.

**Comment by shawnwildermuth** [comment]
Fixed
